# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "en"

#Faster Mitie 
#pipeline:
#- name: "MitieNLP"
#  model: "data/total_word_feature_extractor.dat"
#- name: "MitieTokenizer"
#- name: "MitieEntityExtractor"
#- name: "EntitySynonymMapper"
#- name: "RegexFeaturizer"
#- name: "MitieIntentClassifier"

#Mitie Standard Pipeline
# pipeline: 
# - name: "MitieNLP"
#   model: "data/total_word_feature_extractor.dat"
# - name: "MitieTokenizer"
# - name: "MitieEntityExtractor"
# - name: "EntitySynonymMapper"
# - name: "RegexFeaturizer"
# - name: "MitieFeaturizer"
# - name: "SklearnIntentClassifier"

#Supervised Embeddings
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.5
    core_threshold: 0.3
    fallback_core_action_name: "action_default_ask_affirmation"
    fallback_nlu_action_name: "action_default_fallback"
    deny_suggestion_intent_name: "out_of_scope"

